[application]
http_server_ip = "0.0.0.0"
http_server_port = 8060

[[verifiers_config]]
id = 1
address = "http://localhost:8081"

[[verifiers_config]]
id = 2
address = "http://localhost:8082"

[[verifiers_config]]
id = 3
address = "http://localhost:8083"
