[package]
name = "gateway_rune_transfer"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true }
eyre = { workspace = true }
gateway_config_parser = { workspace = true }
global_utils = { workspace = true }
ord-rs = { workspace = true }
ordinals = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
enum_dispatch = { workspace = true }
