[package]
name = "gateway_rune_transfer"
version = "0.1.0"
edition = "2024"

[dependencies]
ord-rs = { workspace = true }
bitcoin = { workspace = true }
thiserror = { workspace = true }
ordinals = { workspace = true }
serde = { workspace = true }
global_utils = { workspace = true }
