[package]
name = "gateway_config_parser"
edition = "2024"

[dependencies]
global_utils = { workspace = true }
serde = { workspace = true }
config = { workspace = true }
bitcoin = { workspace = true }
spark_client = { workspace = true }
btc_indexer_config = { workspace = true }

[dev-dependencies]
