[package]
name = "verifier_config_parser"
edition = "2024"

[dependencies]
serde = { workspace = true }
config = { workspace = true }
global_utils = { workspace = true }
bitcoin = { workspace = true }
