[package]
name = "verifier_spark_balance_checker_client"
edition = "2024"

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
token-identifier = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
verifier_config_parser = { workspace = true }
uuid = { workspace = true }
url = { workspace = true }
verifier_local_db_store = { workspace = true }
spark_balance_checker_server = { workspace = true }
