
include:
  - ../../btc_indexer/infrastructure/docker-compose.yml
#  - ./verifier/infrastructure/docker-compose.yaml


services:
  verifier_1:
    build:
      context: ../../

#      dockerfile: ./verifier/infrastructure/docker-compose.yml
#    ports:
#      - "8081:8070"
#  verifier_2:
#    build:
#      context: ../../../
#      dockerfile: ./verifier/infrastructure/docker-compose.yml
#    ports:
#      - "8081:8070"
#  verifier_3:
#    build:
#      context: ../../../
#      dockerfile: ./verifier/infrastructure/docker-compose.yml
#    ports:
#      - "8081:8070"


volumes:
  gateway-data:
  verifier-data:
  titan-data: