version: '3.8'

name: runes-spark-bridge
services:
  postgres-gateway:
    image: postgres:17.5-alpine3.22
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/pgdata
    volumes:
      - service-data:/pgdata

volumes:
  service-data: