[package]
name = "spark_balance_checker_config_parser"
edition = { workspace = true }

[dependencies]
bitcoin = { workspace = true }
config = { workspace = true }
serde = { workspace = true }
spark_client = { workspace = true }
sparkscan = { workspace = true }
