[network_config]
network = "regtest"

[application]
http_server_ip = "0.0.0.0"
http_server_port = 8060

[[verifiers_config]]
id = 1
address = "http://verifier-1-svc:8070"
public_key="031c854e841de7983e201bd110a62c58374e8db2c95e626b5c940d9ca656f1dc53"

[[verifiers_config]]
id = 2
address = "http://verifier-2-svc:8070"
public_key="037f3486ec5db1183a187ff233f9f31d68323dd7788f469405d98aef9c77a58346"

[[verifiers_config]]
id = 3
address = "http://verifier-3-svc:8070"
public_key="03dedac4ad6461af9d45369a94cc06ea7663ff531d69ebcfdfad7190dface103df"

[aggregator_config]
threshold = 2
total_participants = 3
update_interval_milliseconds = 10000

[flow_processor_config]
cancellation_retries = 10

[dkg_pregen_config]
update_interval_millis = 1000
min_threshold = 50
max_cached = 500

[database_config]
url = "postgres://gateway:gateway@gateway-db/gateway"

[spark_config]
certificates = [
    { path = "/Amazon-Root-CA.pem" },
    { path = "/Flashnet-CA.pem" },
]

[[spark_config.operators]]
id = 1
base_url = "https://0.spark.lightspark.com"
identity_public_key = "03dfbdff4b6332c220f8fa2ba8ed496c698ceada563fa01b67d9983bfc5c95e763"
frost_identifier = "0000000000000000000000000000000000000000000000000000000000000001"
running_authority = "Lightspark"
is_coordinator = true

[[spark_config.operators]]
id = 2
base_url = "https://1.spark.lightspark.com"
identity_public_key = "03e625e9768651c9be268e287245cc33f96a68ce9141b0b4769205db027ee8ed77"
frost_identifier = "0000000000000000000000000000000000000000000000000000000000000002"
running_authority = "Lightspark"

[[spark_config.operators]]
id = 3
base_url = "https://2.spark.flashnet.xyz"
identity_public_key = "022eda13465a59205413086130a65dc0ed1b8f8e51937043161f8be0c369b1a410"
frost_identifier = "0000000000000000000000000000000000000000000000000000000000000003"
running_authority = "Flashnet"

[bitcoin_client_config]
# url = "https://mempool.space/testnet4/api/"
url = "http://bitcoind:18443"
username = "bitcoin"
password = "bitcoinpass"

[bitcoin_indexer_client_config]
# type = "maestro"
# key = "maestro_api_key"
# confirmation_threshold = 0
type = "titan"
url = "http://titan:3030"

[fee_config]
amount=1000
btc_address="bcrt1pwzj4xdxrdsjl900sq62982tmcehjv2hc22glzumzxyxx2ctetrjq7u3vfz"
spark_address="sprt1pgss8ac0a8nlywyvgyna0uws4jkcm9uaycu7mxdp0atxf7cf30rnw4kv5x85wf"
