[package]
name = "verifier_server"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
bitcoin = { workspace = true }
frost = { workspace = true }
global_utils = { workspace = true }
persistent_storage = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
titan-client = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
verifier_btc_indexer_client = { workspace = true }
verifier_config_parser = { workspace = true }
verifier_gateway_client = { workspace = true }
verifier_local_db_store = { workspace = true }
verifier_spark_balance_checker_client = { workspace = true }
token-identifier = { workspace = true }

[dev-dependencies]
axum-test = { workspace = true }
sqlx = { workspace = true }
