[package]
name = "verifier_server"
edition = "2024"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
verifier_config_parser = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
verifier_local_db_store = { workspace = true }