[package]
name = "spark-invoice"
edition = "2024"

[dependencies]
token-identifier = { workspace = true }
bitcoin = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
eyre = { workspace = true }
