[application]
http_server_ip = "0.0.0.0"
http_server_port = 8072
network = "Regtest"

[btc_indexer_url_config]
address="localhost:8079"

[spark_balance_checker_url_config]
address="localhost:8078"

[frost_signer]
identifier = 2
threshold = 2
total_participants = 3
