[application]
http_server_ip = "0.0.0.0"
http_server_port = 8072
network = "bitcoin"

[btc_indexer_url_config]
address="http://localhost:8070"

[spark_balance_checker_url_config]
address="http://localhost:8090"

[frost_signer_config]
identifier = 2
threshold = 2
total_participants = 3

[gateway_config]
address = "http://localhost:8060"

[database_config]
url = "postgres://davicoscarelli:davi2304@localhost:5432/runes_verifier_2"
