[application]
http_server_ip = "0.0.0.0"
http_server_port = 8070
network = "regtest"

[btc_indexer_url_config]
address="http://btc-indexer-service:8070"

[spark_balance_checker_url_config]
address="http://spark-balance-checker-service:8070"

[frost_signer_config]
identifier = 2
threshold = 2
total_participants = 3

[gateway_config]
address = "http://gateway-service:8060"
