[application]
http_server_ip = "0.0.0.0"
http_server_port = 8070
network = "bitcoin"

[btc_indexer_url_config]
address="http://btc-indexer-service:8070"

[spark_balance_checker_url_config]
address="http://spark-balance-checker-service:8070"

[frost_signer_config]
identifier = 2
threshold = 2
total_participants = 3

[gateway_config]
address = "http://gateway-service:8060"

[database_config]
url = "postgres://admin_manager:password@persistent-db-storage_verifier_2:5432/production_db_name"

[fee_config]
amount=1000
btc_address="bcrt1pwzj4xdxrdsjl900sq62982tmcehjv2hc22glzumzxyxx2ctetrjq7u3vfz"
spark_address="sprt1pgss8ac0a8nlywyvgyna0uws4jkcm9uaycu7mxdp0atxf7cf30rnw4kv5x85wf"
