[application]
http_server_ip = "127.0.0.1"
http_server_port = 8060
btc_network = "regtest"
spark_network = "Regtest"

[[verifiers_config]]
id = 1
address = "http://localhost:8071"

[[verifiers_config]]
id = 2
address = "http://localhost:8072"

[[verifiers_config]]
id = 3
address = "http://localhost:8073"

[aggregator_config]
threshold = 2
total_participants = 3

[flow_processor_config]
cancellation_retries = 10
