[network_config]
network = "bitcoin"

[application]
http_server_ip = "127.0.0.1"
http_server_port = 8060

[[verifiers_config]]
id = 1
address = "http://127.0.0.1:8071"
public_key = "02ca87e05fb76d0455a78cfdde4ed4d3e459682f41bc4b66d63cbc7c8f0fee5db5"

[[verifiers_config]]
id = 2
address = "http://127.0.0.1:8072"
public_key = "02e433425b709263954fa94218eca4deffc22392682f1fe13364cc9437ae4813e6"

[[verifiers_config]]
id = 3
address = "http://127.0.0.1:8073"
public_key = "02ede6320e81ccf8134af95134b7b64e06e65c580ceeb414ef8aeeda1196bc384e"

[aggregator_config]
threshold = 2
total_participants = 3
update_interval_milliseconds = 10000

[flow_processor_config]
cancellation_retries = 10

[dkg_pregen_config]
update_interval_millis = 1000
min_threshold = 50
max_cached = 500

[database_config]
url = "postgres://davicoscarelli:davi2304@localhost:5432/runes_gateway"

[spark_config]
certificates = [
    { path = "./infrastructure/configurations/certificates/Amazon-Root-CA.pem" },
    { path = "./infrastructure/configurations/certificates/Flashnet-CA.pem" },
]

[[spark_config.operators]]
id = 1
base_url = "https://0.spark.lightspark.com"
identity_public_key = "03dfbdff4b6332c220f8fa2ba8ed496c698ceada563fa01b67d9983bfc5c95e763"
frost_identifier = "0000000000000000000000000000000000000000000000000000000000000001"
running_authority = "Lightspark"
is_coordinator = true

[[spark_config.operators]]
id = 2
base_url = "https://1.spark.lightspark.com"
identity_public_key = "03e625e9768651c9be268e287245cc33f96a68ce9141b0b4769205db027ee8ed77"
frost_identifier = "0000000000000000000000000000000000000000000000000000000000000002"
running_authority = "Lightspark"

[[spark_config.operators]]
id = 3
base_url = "https://2.spark.flashnet.xyz"
identity_public_key = "022eda13465a59205413086130a65dc0ed1b8f8e51937043161f8be0c369b1a410"
frost_identifier = "0000000000000000000000000000000000000000000000000000000000000003"
running_authority = "Flashnet"

[bitcoin_client_config]
url = "https://mempool.space/api/"

[bitcoin_indexer_client_config]
type = "maestro"
url = "https://xbt-mainnet.gomaestro-api.org/v0/"
key = "WJTMnRcKf3bgtWgooCrL9FB2FVOPii4q"
confirmation_threshold = 3

# Uncomment and update if mainnet fee collection is required.
# [fee_config]
# amount = 1000
# btc_address = "bc1..."
# spark_address = "sprt1..."
