[network_config]
network = "bitcoin"

[application]
http_server_ip = "0.0.0.0"
http_server_port = 8060

[[verifiers_config]]
id = 1
address = "http://verifier1-service:8070"

[[verifiers_config]]
id = 2
address = "http://verifier2-service:8070"

[[verifiers_config]]
id = 3
address = "http://verifier3-service:8070"

[aggregator_config]
threshold = 2
total_participants = 3
update_interval_milliseconds = 10000

[flow_processor_config]
cancellation_retries = 10

[dkg_pregen_config]
update_interval_millis = 1000
min_threshold = 50
max_cached = 500

[database_config]
url = "postgres://admin_manager:password@persistent-db-storage_gateway:5432/production_db_name"

[spark_config]
certificates = [
    { path = "./configuration_gateway/Amazon-Root-CA.pem" },
    { path = "./configuration_gateway/Flashnet-CA.pem" },
]

[[spark_config.operators]]
id = 1
base_url = "https://0.spark.lightspark.com"
identity_public_key = "03dfbdff4b6332c220f8fa2ba8ed496c698ceada563fa01b67d9983bfc5c95e763"
frost_identifier = "0000000000000000000000000000000000000000000000000000000000000001"
running_authority = "Lightspark"
is_coordinator = true

[[spark_config.operators]]
id = 2
base_url = "https://1.spark.lightspark.com"
identity_public_key = "03e625e9768651c9be268e287245cc33f96a68ce9141b0b4769205db027ee8ed77"
frost_identifier = "0000000000000000000000000000000000000000000000000000000000000002"
running_authority = "Lightspark"

[bitcoin_client_config]
url = "http://bitcoind:18443"
username = "bitcoin"
password = "bitcoinpass"

[bitcoin_indexer_client_config]
type = "titan"
url = "http://localhost:3030"

[fee_config]
amount=1000
btc_address="bcrt1pwzj4xdxrdsjl900sq62982tmcehjv2hc22glzumzxyxx2ctetrjq7u3vfz"
spark_address="sprt1pgss8ac0a8nlywyvgyna0uws4jkcm9uaycu7mxdp0atxf7cf30rnw4kv5x85wf"
