[network_config]
network = "regtest"

[application]
http_server_ip = "0.0.0.0"
http_server_port = 8060

[[verifiers_config]]
id = 1
address = "http://verifier1-service:8070"

[[verifiers_config]]
id = 2
address = "http://verifier2-service:8070"

[[verifiers_config]]
id = 3
address = "http://verifier3-service:8070"

[aggregator_config]
threshold = 2
total_participants = 3
update_interval_milliseconds = 10000

[flow_processor_config]
cancellation_retries = 10

[database_config]
url = "postgres://postgres:postgres@postgres-gateway:5432/gateway"
