[package]
name = "gateway_runes_utxo_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bitcoin = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
persistent_storage = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
