[package]
name = "verifier-main"
edition = "2024"

[dependencies]
verifier-common = { workspace = true }
verifier-server = { workspace = true }
tokio = { workspace = true }
global-utils = { workspace = true }
log = { workspace = true }