[package]
name = "verifier_main"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
dotenvy = { workspace = true }
global_utils = { workspace = true }
persistent_storage = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
verifier_config_parser = { workspace = true }
verifier_local_db_store = { workspace = true }
verifier_server = { workspace = true }
frost = { workspace = true }
eyre = { workspace = true }
