name: runes-spark-bridge
services:

  persistent-db-storage:
    image: postgres:17.5-alpine3.22
    restart: always
    networks:
      verifier-network:
        ipv4_address: 172.28.0.2
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin_manager}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_HOST=persistent-db-storage
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-production_db_name}
      - PGDATA=/pgdata
    volumes:
      - service-data:/pgdata

  verifier-service:
    build:
      context: ./../../
      dockerfile: ./verifier/infrastructure/Dockerfile
    restart: always
    networks:
      verifier-network:
        ipv4_address: 172.28.0.3
    environment:
      - RUST_LOG=trace
      - APP_ENVIRONMENT=production
      - DATABASE_URL=postgres://${POSTGRES_USER:-admin_manager}:${POSTGRES_PASSWORD:-password}@persistent-db-storage:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-production_db_name}
    ports:
      - "8080:8070"
    entrypoint: sh -c "sqlx migrate run && verifier_main"
    depends_on:
      - persistent-db-storage
    volumes:
      - ./configuration/production.toml:/configuration_verifier/production.toml

networks:
  verifier-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

volumes:
  service-data: