[package]
name = "spark_balance_checker_server"
edition = { workspace = true }

[features]
default = []

[dependencies]
axum = { workspace = true }
serde = { workspace = true }
spark_client = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
hex = { workspace = true }
spark-protos = { workspace = true }
spark-address = { workspace = true }
token-identifier = { workspace = true }
bitcoin = { workspace = true }
