[package]
name = "spark_balance_checker_server"
edition = { workspace = true }

[features]
default = []
swagger = []

[dependencies]
axum = { workspace = true }
bech32 = { workspace = true }
global_utils = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
spark-address = { workspace = true }
spark-protos = { workspace = true }
spark_client = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tonic-health = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }

[dev-dependencies]
anyhow = { workspace = true }
axum-test = { workspace = true }
dotenvy = { workspace = true }
tokio = { workspace = true }
spark_balance_checker_config_parser = { workspace = true }
