[package]
name = "gateway_flow_processor"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
bitcoin = { workspace = true }
frost = { workspace = true }
gateway_config_parser = { workspace = true }
gateway_local_db_store = { workspace = true }
gateway_rune_transfer = { workspace = true }
gateway_spark_service = { workspace = true }
global_utils = { workspace = true }
persistent_storage = { workspace = true }
spark-address = { workspace = true }
spark_client = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
btc_indexer_client = { workspace = true }

[dev-dependencies]
