[server]
hostname = "0.0.0.0:8070"

[btc_indexer]
update_interval_millis = 1000
validation_timeout_millis = 1000
confirmation_block_height_delta = 6

[database]
url = "postgres://postgres:postgres@localhost:5474/btc_indexer"

[network]
network = "regtest"

[indexer_client]
url = "http://localhost:3030"
