[server]
hostname = "0.0.0.0:8070"

[btc_indexer]
indexer_update_interval_millis = 1000
validation_timeout_millis = 1000
confirmation_block_height_delta = 6
tx_indexer_update_interval_millis = 1000
start_block_height = 0

[database]
url = "postgres://postgres:postgres@127.0.0.1:5474/btc_indexer"

[network]
network = "regtest"

[indexer_client]
url = "http://127.0.0.1:3030"
