[network_config]
network = "regtest"

[application]
http_server_ip = "127.0.0.1"
http_server_port = 8060

[[verifiers_config]]
id = 1
address = "http://127.0.0.1:8071"

[[verifiers_config]]
id = 2
address = "http://127.0.0.1:8072"

[[verifiers_config]]
id = 3
address = "http://127.0.0.1:8073"

[aggregator_config]
threshold = 2
total_participants = 3
update_interval_milliseconds = 10000

[flow_processor_config]
cancellation_retries = 10

[dkg_pregen_config]
update_interval_millis = 1000
min_threshold = 50
max_cached = 500

[database_config]
url = "postgres://postgres:postgres@127.0.0.1:5432/gateway"

[spark_config]
certificates = [
    { path = "Amazon-Root-CA.pem" },
    { path = "Flashnet-CA.pem" },
]

[[spark_config.operators]]
id = 1
base_url = "https://0.spark.lightspark.com"
identity_public_key = "03dfbdff4b6332c220f8fa2ba8ed496c698ceada563fa01b67d9983bfc5c95e763"
frost_identifier = "0000000000000000000000000000000000000000000000000000000000000001"
running_authority = "Lightspark"
is_coordinator = true

[[spark_config.operators]]
id = 2
base_url = "https://1.spark.lightspark.com"
identity_public_key = "03e625e9768651c9be268e287245cc33f96a68ce9141b0b4769205db027ee8ed77"
frost_identifier = "0000000000000000000000000000000000000000000000000000000000000002"
running_authority = "Lightspark"

[[spark_config.operators]]
id = 3
base_url = "https://2.spark.flashnet.xyz"
identity_public_key = "022eda13465a59205413086130a65dc0ed1b8f8e51937043161f8be0c369b1a410"
frost_identifier = "0000000000000000000000000000000000000000000000000000000000000003"
running_authority = "Flashnet"

[bitcoin_client_config]
# url = "https://mempool.space/testnet4/api/"
url = "http://127.0.0.1:18443"
username = "bitcoin"
password = "bitcoinpass"

[bitcoin_indexer_client_config]
# type = "maestro"
# key = "maestro_api_key"
# confirmation_threshold = 0
type = "titan"
url = "http://127.0.0.1:3030"

[fee_config]
amount=1000
btc_address="bcrt1pwzj4xdxrdsjl900sq62982tmcehjv2hc22glzumzxyxx2ctetrjq7u3vfz"
spark_address="sprt1pgss8ac0a8nlywyvgyna0uws4jkcm9uaycu7mxdp0atxf7cf30rnw4kv5x85wf"
