[package]
name = "spark-balance-checker-main"
edition = { workspace = true }

[features]
default = []
swagger = ["spark-balance-checker-server/swagger"]

[dependencies]
spark-balance-checker-server = { workspace = true }
spark-balance-checker-common = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }