[application]
http_server_ip = "0.0.0.0"
http_server_port = 8073
network = "regtest"

[btc_indexer_url_config]
address="http://localhost:8070"

[spark_balance_checker_url_config]
address="http://localhost:8090"

[frost_signer_config]
identifier = 3
threshold = 2
total_participants = 3

[gateway_config]
address = "http://localhost:8060"

[database_config]
url = "postgres://postgres:postgres@localhost:5473/verifier"

[fee_config]
amount=1000
btc_address="bcrt1pwzj4xdxrdsjl900sq62982tmcehjv2hc22glzumzxyxx2ctetrjq7u3vfz"
spark_address="sprt1pgss8ac0a8nlywyvgyna0uws4jkcm9uaycu7mxdp0atxf7cf30rnw4kv5x85wf"
