[application]
http_server_ip = "0.0.0.0"
http_server_port = 8073
network = "regtest"

[btc_indexer_url_config]
address="http://localhost:8079"

[spark_balance_checker_url_config]
address="http://localhost:8078"

[frost_signer_config]
identifier = 3
threshold = 2
total_participants = 3

[gateway_config]
address = "http://localhost:8060"
