[application]
http_server_ip = "0.0.0.0"
http_server_port = 8073
network = "bitcoin"
callback_url = "http://127.0.0.1:8073/api/btc-indexer/notify-runes-deposit"
secret_key = "2c14e4446865a72658a59168e99bde1a12297b8b72861cabdaa0e9b5c6cffbf3"

[btc_indexer_url_config]
address = "http://127.0.0.1:8070"

[spark_balance_checker_url_config]
address = "http://127.0.0.1:8090"

[frost_signer_config]
identifier = 3
threshold = 2
total_participants = 3

[gateway_config]
address = "http://127.0.0.1:8060"

[database_config]
url = "postgres://davicoscarelli:davi2304@localhost:5432/runes_verifier_3"

# Uncomment and update if on-chain fee collection is required.
# [fee_config]
# amount = 1000
# btc_address = "bc1..."
# spark_address = "sprt1..."
