[package]
name = "gateway_server"
edition = "2024"

[dependencies]
axum = { workspace = true }
axum-test = { workspace = true }
bitcoin = { workspace = true }
eyre = { workspace = true }
frost = { workspace = true }
gateway_config_parser = { workspace = true }
gateway_deposit_verification = { workspace = true }
gateway_dkg_pregen = { workspace = true }
gateway_flow_processor = { workspace = true }
gateway_local_db_store = { workspace = true }
gateway_rune_transfer = { workspace = true }
gateway_verifier_client = { workspace = true }
global_utils = { workspace = true }
persistent_storage = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
titan-client = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
frost-secp256k1-tr = { workspace = true }
gateway_config_parser = { workspace = true }
gateway_verifier_client = { workspace = true }
serde_json = { workspace = true }
spark_client = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
verifier_server = { workspace = true }
