[package]
name = "spark-client"
edition = { workspace = true }

[dependencies]
spark-protos = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
eyre = { workspace = true }
bech32 = { workspace = true }
env_logger = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }