[package]
name = "verifier_local_db_store"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
tracing = { workspace = true }
persistent_storage = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
sqlx = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }