name: runes-spark-bridge_databases
services:
  # ====== Gateway Database ======
  postgres-gateway:
    image: postgres:17.5-alpine3.22
    restart: always
    ports:
      - "5470:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-gateway}
      - PGDATA=/pgdata
    volumes:
      - service-data_gateway:/pgdata

  # ====== Verifier 1 Database ======
  postgres-verifier_1:
    image: postgres:17.5-alpine3.22
    restart: always
    ports:
      - "5471:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-verifier}
      - PGDATA=/pgdata
    volumes:
      - service-data_verifier_1:/pgdata

  # ====== Verifier 2 Database ======
  postgres-verifier_2:
    image: postgres:17.5-alpine3.22
    restart: always
    ports:
      - "5472:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-verifier}
      - PGDATA=/pgdata
    volumes:
      - service-data_verifier_2:/pgdata

  # ====== Verifier 3 Database ======
  postgres-verifier_3:
    image: postgres:17.5-alpine3.22
    restart: always
    ports:
      - "5473:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-verifier}
      - PGDATA=/pgdata
    volumes:
      - service-data_verifier_3:/pgdata

  # ====== BTC Indexer Database ======
  postgres-btc_indexer:
    image: postgres:17.5-alpine3.22
    restart: always
    ports:
      - "5474:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-btc_indexer}
      - PGDATA=/pgdata
    volumes:
      - service-data_btc_indexer:/pgdata

volumes:
  service-data_gateway:
  service-data_verifier_1:
  service-data_verifier_2:
  service-data_verifier_3:
  service-data_btc_indexer:
