[application]
http_server_ip = "0.0.0.0"
http_server_port = 8083

[btc_indexer_url_config]
address="localhost:8050"

[spark_balance_checker_url_config]
address="localhost:8070"

[frost_signer_config]
identifier = 3
threshold = 2
total_participants = 3
