[package]
name = "gateway_dkg_pregen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
readme.workspace = true

[dependencies]
eyre = { workspace = true }
frost = { workspace = true }
gateway_config_parser = { workspace = true }
gateway_local_db_store = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
persistent_storage = { workspace = true }
sqlx = { workspace = true }
frost-secp256k1-tr = { workspace = true }
global_utils = { workspace = true }

