[server]
address = "0.0.0.0:8090"

[postgres]
url = "postgresql://postgres:postgres@localhost:5434/verifier1"

[btc-indexer]
address = "http://localhost:8081"

[spark-balance-checker]
address = "http://localhost:8082"
