[application]
http_server_ip = "0.0.0.0"
http_server_port = 8070

[[spark_operators]]
id = 1
base_url = "https://0.spark.lightspark.com"
identity_public_key = "03dfbdff4b6332c220f8fa2ba8ed496c698ceada563fa01b67d9983bfc5c95e763"
frost_identifier = "0000000000000000000000000000000000000000000000000000000000000001"
running_authority = "Lightspark"
is_coordinator = true

[[spark_operators]]
id = 2
base_url = "https://1.spark.lightspark.com"
identity_public_key = "03e625e9768651c9be268e287245cc33f96a68ce9141b0b4769205db027ee8ed77"
frost_identifier = "0000000000000000000000000000000000000000000000000000000000000002"
running_authority = "Lightspark"
