[application]
http_server_ip = "0.0.0.0"
http_server_port = 8090

[network]
network = "bitcoin"

[sparkscan]
base_url = "https://api.sparkscan.io"
api_key = "ss_sk_live_HfLDKdtU-m-sUQhTqbkUe3FMDtYhUvHH0MkbnhKHPCJf4IUKDHZ2V"

[spark_config]
certificates = [
    { path = "./infrastructure/configurations/certificates/Amazon-Root-CA.pem" },
    { path = "./infrastructure/configurations/certificates/Flashnet-CA.pem" },
]

[[spark_config.operators]]
id = 1
base_url = "https://0.spark.lightspark.com"
identity_public_key = "03dfbdff4b6332c220f8fa2ba8ed496c698ceada563fa01b67d9983bfc5c95e763"
frost_identifier = "0000000000000000000000000000000000000000000000000000000000000001"
running_authority = "Lightspark"

[[spark_config.operators]]
id = 2
base_url = "https://1.spark.lightspark.com"
identity_public_key = "03e625e9768651c9be268e287245cc33f96a68ce9141b0b4769205db027ee8ed77"
frost_identifier = "0000000000000000000000000000000000000000000000000000000000000002"
running_authority = "Lightspark"

[[spark_config.operators]]
id = 3
base_url = "https://2.spark.flashnet.xyz"
identity_public_key = "022eda13465a59205413086130a65dc0ed1b8f8e51937043161f8be0c369b1a410"
frost_identifier = "0000000000000000000000000000000000000000000000000000000000000003"
running_authority = "Flashnet"
is_coordinator = true
