[package]
name = "gateway_main"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
gateway_config_parser = { workspace = true }
gateway_server = { workspace = true }
global_utils = { workspace = true }
persistent_storage = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
